### ISSUE TITLE
Issue Description

### ISSUE THREAD

**Issue by mckernanin** [manavo/donedone-api-php#3]
I'm trying to get the description of an issue, and I'm not having any luck. 
I'm getting issues by doing $issues = $client->project( 50291 )->issues();
Then I was trying to get the description by doing:

```
    $description  = $client->project( 50291 )->issue( 1 );
    $description  = $description->toArray();
    var_dump($description);
```

This dumps the following:

array (size=4)
  'title' => null
  'priority_level_id' => null
  'fixer_id' => null
  'tester_id' => null

**Comment by manavo** [comment]
Hey! There wasn't a way to do it yet, so I've just added it. You can now do it like this:

```
    $issue  = $client->project( 50291 )->issue( 1 )->get();
    var_dump($issue);
```

Just update to the latest version of the library via composer (I just made a new release).

I've added this for projects and issues, not the rest of the models yet.

**Comment by mckernanin** [comment]
Woohoo! Thanks!
